### ISSUE TITLE
misplaced arguments in the bash script

### ISSUE THREAD

**Issue by TaoZheng9** [JiangpengHe/imbalanced_cil#1]
Hello, thanks for sharing this code. but I found these bash script arguments are misplaced. For example, the first case treat DGR as GPU:

bash main.sh Food101 DGR 0 ltio 51 6
Running approach: Food101
Running on gpu: DGR
Project dir: /home/tao/imb/imbalanced_cil_cvpr24
Sources dir: /home/tao/imb/imbalanced_cil_cvpr24/src
Results dir: /home/tao/imb/imbalanced_cil_cvpr24/0
No scenario provided.

and this case,  the ltio is not treated as the scenario
bash main.sh DGR 0 ltio 51 6
Running approach: DGR
Running on gpu: 0
Project dir: /home/tao/imb/imbalanced_cil_cvpr24
Sources dir: /home/tao/imb/imbalanced_cil_cvpr24/src
Results dir: /home/tao/imb/imbalanced_cil_cvpr24/ltio
No scenario provided.

**Comment by TaoZheng9** [comment]
> Hello, thanks for sharing this code. but I found these bash script arguments are misplaced. For example, the first case treat DGR as GPU:
> 
> bash main.sh Food101 DGR 0 ltio 51 6 Running approach: Food101 Running on gpu: DGR Project dir: /home/tao/imb/imbalanced_cil_cvpr24 Sources dir: /home/tao/imb/imbalanced_cil_cvpr24/src Results dir: /home/tao/imb/imbalanced_cil_cvpr24/0 No scenario provided.
> 
> and this case, the ltio is not treated as the scenario bash main.sh DGR 0 ltio 51 6 Running approach: DGR Running on gpu: 0 Project dir: /home/tao/imb/imbalanced_cil_cvpr24 Sources dir: /home/tao/imb/imbalanced_cil_cvpr24/src Results dir: /home/tao/imb/imbalanced_cil_cvpr24/ltio No scenario provided.

Then, I found that this was only an issue in the Readme.MD, you just have to change the argument places:
from 
```<dataset> <approach> <gpu> <scenario> <initial_classes> <total_tasks>```
to 
```<approach> <gpu> <dataset> <scenario> <initial_classes> <total_tasks>```
like
bash main.sh DGR 0 cifar100 conv 5 20
then everything is fine

**Comment by JiangpengHe** [comment]
Hi, 
Thanks for pointing this out! I have made the changes and updated the readme file.
