### ISSUE TITLE
Reproducing Food101 results

### ISSUE THREAD

**Issue by amoeba04** [JiangpengHe/imbalanced_cil#3]
Thank you for sharing your work.

I can only see the readme file of datasets. ([https://github.com/JiangpengHe/imbalanced_cil/blob/main/data/Readme.md#food-101](url))

Would you share details for generating train.txt and test.txt, or share the raw train.txt and test.txt of Food101 dataset?

**Comment by JiangpengHe** [comment]
We have updated the readme file for dataset file generation, please let us know if there are further questions, thanks.
